### ISSUE TITLE
Pod log output is not passed on time to caller

### ISSUE THREAD

**Issue by igor-teresco** [joyrex2001/kubedock#114]
We are having a strange issue with latest kubedock in gradle build:
1. testcontainers is creating a postgres pod for test execution, it is initialized ok, pog log shows that database is waiting for connections [kubedock-pod.log](https://github.com/user-attachments/files/18183263/kubedock-pod.log)
2. but test is still waiting for kubedock to return that log output and confirm that pod is ready, that takes 1 minute sharp 
[gradle-buildah-agent.log](https://github.com/user-attachments/files/18183355/gradle-buildah-agent.log)
3. after that timeout test is considered failed:
```
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image postgres:16.3
	at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
	at app//org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
	at app//org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:134)
	at app//com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at app//com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at app//com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at app//com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at app//com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550)
	... 60 more
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at app//org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:344)
	... 67 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at app//org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:563)
	at app//org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:354)
	at app//org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 68 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*database system is ready to accept connections.*\s'
	at app//org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)
	at app//org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
	at app//org.testcontainers.containers.PostgreSQLContainer.waitUntilContainerStarted(PostgreSQLContainer.java:149)
	at app//org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:500)
```

**Comment by ErikEngerd** [comment]
do you have a sime reproducible case?

**Comment by ErikEngerd** [comment]
With the latest updates to ioproxy a really dodgy issue was solved whereby data could be written to another connection because of a delayed flush in combination with a gin.Context object that was being reused. 

Looking closely at the code now, I see that there are cases where ioproxy does not write all data. This can happen in the case of short writes to the client. That can be fixed at least. I will have a look at that this weekend.

**Comment by igor-teresco** [comment]
sadly can't paste relevant parts of code as developer in charge is away now.
Can add that while investigating this, he extended the JdbcDatabaseContainerProvider class to be able to increase the waiting timeout and that had helped. Test was successfully finished, but that 1 minute had grew in 5 minutes....
Note the 5 min gap:
```
    2024-12-17T15:07:09.637Z DEBUG 330 --- [    Test worker] [                                                 ] o.t.containers.output.WaitingConsumer    : STDOUT: 2024-12-17 15:02:09.539 UTC [1] LOG:  database system is ready to accept connections
    2024-12-17T15:07:09.640Z  INFO 330 --- [    Test worker] [                                                 ] c.v.n.util.ExtLogMessageWaitStrategy     : End waitUntilReady() for .*database system is ready to accept 
```

**Comment by igor-teresco** [comment]
Forgot to mention one important thing, test was working fine until we changed postgres image from 11.16 to 13.6

**Comment by ErikEngerd** [comment]
Was also looking at the patch I made for #106. I think there a are some places in the code where the contract of Reader and Writer is not used correctly. In particular, both Read and Write can return n > 0 in combination with an err != nil. This means that in dealing with these methods, the  n > 09 case should be handled before dealing with the error. Otherwise data can be missing. 

Additionaly, I thought it would be a good idea to use io.Copy() to address these problems instead of writing for loops for copying data, but it turns out that when using io.Copy() and in one step data written is less than data read (nw < nr), then ErrShortWrite is returned. I found this in ioproxy_test.go to which I added some short write tests as part of #106. This is completely unexpected and disagrees with the io.Copy() description in my opinion. Looking at the code, io.Copy() is used in other places as well so this is also vulnerable to this condition. So, I think there are several improvements that can still be done in this area.

I think I will submit two patches for this: one to address the issue with logs specifically and introduce an new ioutil.Copy() function that deals with ErrShortWrite returned from io.Copy() and then another one to replace other invocations of io.Copy() with the new implementation. 

@igor-teresco  It would be interesting still to know whether the issue still occurs with the previous version of kubedock. Also, whether it occurs every time or only in a percentage of cases. BTW. do you know that you are using the latest kubedock from the master branch and not the latest release?

**Comment by ErikEngerd** [comment]
In my testing, I haven't found any cases where either (1) short writes occurred or (2) bytes were read with at the same time an error returned (backend/logs.go). These were the suspect cases that could lead to incomplete log output. 

So I could submit a patch but I am doubtful whether it will solve this issue. Perhaps there is something different in your network stack that causes this issue. 

Alternatively, we definitely need to make sure that no buffering is going on in your container. So perhaps start the container with a TTY, or (more robust) wrap the containers entrypoint like this 

```
stdbuf -o0 -e0 /path/to/original/entrypoint.sh
```

**Comment by igor-teresco** [comment]
- With 0.17.0 image version all is working fine (logs attached). With latest 0.17.1 issue was manifesting each time, very stable :-).
- (regarding TTY) Not quite sure how to implement this, sorry
- We are using docker image by label "image: "joyrex2001/kubedock:latest" - ain't this latest release?
[gradle-buildah-agent-0.17.0.log](https://github.com/user-attachments/files/18226858/gradle-buildah-agent-0.17.0.log)
[kubedock-pod-0.17.0.log](https://github.com/user-attachments/files/18226859/kubedock-pod-0.17.0.log)

**Comment by ErikEngerd** [comment]
We are using docker image by label "image: "joyrex2001/kubedock:latest" - ain't this latest release?

Looking at the original logs, I see this: 

```
I1218 13:10:00.184156       1 main.go:29] kubedock 0.17.1-7-g8528295 (20241213-142345) / kubedock.id=7e0f95d7cf76
```

So you are using the 7th commit after 0.17.1 with commit starting with 8228295 which is the latest on master. 

However, these 7 commits are, I believe, totally unrelated to what you are seeing. I could submit a patch that partly reintroduces the old behavior. That was a behavior that did an automatic flush of the log data to the client 100ms after every write. That was causing issues because it could potentially flush data to another connection after the final write was done. 

But, I can catch this because I know that the length of the data is always 0 in this problematic flush. So I can simply ignore flushes of length 0. So I can fix it to have the original behavior back and still solving the earlier issue. In my code I had 1 in 3 test cases fail before that change. It doesn't feel write to do it like this, but at least you would get back the original behavior if that change was the problematic one.

**Comment by joyrex2001** [comment]
@igor-teresco can you confirm the update fixes the problem?

**Comment by igor-teresco** [comment]
Yes, it works now as before! Many thanks!

**Comment by ErikEngerd** [comment]
> Yes, it works now as before! Many thanks!

happy to hear!
